import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { margin: 10, padding: 10 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#EEE', paddingBottom: 5, marginBottom: 5 },
  label: { width: '40%', fontSize: 10, color: 'gray' },
  value: { width: '60%', fontSize: 10 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#F0F0F0', padding: 5 },
  tableRow: { flexDirection: 'row', padding: 5, borderBottomWidth: 1, borderBottomColor: '#EEE' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, textAlign: 'center', color: 'gray' }
});

// Define the data types
interface BatchPdfProps {
  batch: any; // Using 'any' for simplicity in this guide
}

export const BatchPdfDocument = ({ batch }: BatchPdfProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Batch Production Record</Text>
      
      {/* Batch Details Section */}
      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Product Name:</Text>
          <Text style={styles.value}>{batch.product.name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Batch Code:</Text>
          <Text style={styles.value}>{batch.batchCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date Produced:</Text>
          <Text style={styles.value}>{new Date(batch.producedAt).toLocaleDateString()}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Status:</Text>
          <Text style={styles.value}>{batch.status}</Text>
        </View>
      </View>

      {/* Ingredients Table */}
      <View style={styles.section}>
        <Text style={{ fontSize: 14, marginBottom: 10, fontWeight: 'bold' }}>Ingredients Used</Text>
        
        <View style={styles.tableHeader}>
          <Text style={{ width: '40%', fontSize: 10, fontWeight: 'bold' }}>Ingredient</Text>
          <Text style={{ width: '30%', fontSize: 10, fontWeight: 'bold' }}>Lot #</Text>
          <Text style={{ width: '30%', fontSize: 10, fontWeight: 'bold' }}>Quantity</Text>
        </View>

        {batch.ingredients.map((item: any, i: number) => (
          <View key={i} style={styles.tableRow}>
            <Text style={{ width: '40%', fontSize: 10 }}>{item.ingredient.name}</Text>
            <Text style={{ width: '30%', fontSize: 10 }}>{item.ingredient.lotNumber}</Text>
            <Text style={{ width: '30%', fontSize: 10 }}>{item.amountUsed} {item.ingredient.unit}</Text>
          </View>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by BatchTrace • Compliance Record • Do Not Alter
      </Text>
    </Page>
  </Document>
);